package sink

import (
	"errors"
	"os"
	"time"
)

// These errors classify why a destination folder was refused. They are
// package-private on purpose: the adapter maps each to a transfer.ErrorCode at
// its one public boundary, so a platform file never decides what the UI says.
var (
	errLinkLike     = errors.New("sink: a path component is a symbolic link or reparse point")
	errNotDirectory = errors.New("sink: the destination is not a directory")
	errUnusable     = errors.New("sink: the destination cannot be used")
)

// dirHandle is a pinned directory the sink writes inside.
//
// It is the platform seam. On POSIX every operation is relative to a held
// descriptor, so once the destination has been opened no path is re-resolved and
// a link swapped in above it afterwards changes nothing. On Windows, which has
// no portable openat, the operations are path-based and every path is built by
// joining a name this package generated onto a directory it just created or
// validated.
//
// Names passed to any method are a single path segment generated by this
// package (a sanitized phone name, a temp name, a subfolder name). None is ever
// a path.
type dirHandle interface {
	// mkdirExclusive creates the child directory name with mode 0755 (before
	// umask) and returns a handle to it. It fails with fs.ErrExist when
	// anything, including a link, already has that name, and never follows one.
	mkdirExclusive(name string) (dirHandle, error)
	// rmdir removes the empty child directory name.
	rmdir(name string) error
	// createExclusive creates the regular file name with mode 0644 (before
	// umask), opened for writing. It fails with fs.ErrExist when anything,
	// including a link, already has that name, and never follows one. The mode
	// never carries an execute bit.
	createExclusive(name string) (*os.File, error)
	// renameNoReplace renames the file from to to inside this directory. It
	// fails with fs.ErrExist, changing nothing, when to already exists, and it
	// fails closed when the filesystem offers no way to do that atomically.
	renameNoReplace(from, to string) error
	// unlink removes the file name.
	unlink(name string) error
	// mark applies the OS download marking to the open file named name. It is
	// best-effort: a non-nil error means the marking is absent, never that the
	// file is bad. A platform with no such marking returns nil.
	mark(file *os.File, name string, now time.Time) error
	// availableBytes reports the bytes available to an unprivileged writer on
	// the volume holding this directory.
	availableBytes() (uint64, error)
	// close releases the handle. It is idempotent.
	close() error
}
