// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function StageTransfer(arg1) {
  return window['go']['main']['App']['StageTransfer'](arg1);
}

export function StageTransfers(arg1) {
  return window['go']['main']['App']['StageTransfers'](arg1);
}
