// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {transfer} from '../models';

export function CancelTransfer():Promise<void>;

export function Publish(arg1:transfer.Event):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function StageTransfer(arg1:string):Promise<transfer.FileMetadata>;
